services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: counter_app
    depends_on:
      - db
    networks:
      - counter

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: counter_nginx
    restart: unless-stopped
    volumes:
      - ./client/dist/index.html:/bin/www/dist/index.html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports: 
      - "8080:80"
    depends_on:
      - backend
    networks:
      - counter

  db:
    image: mongo
    container_name: counter_db
    restart: always
    ports:
      - "27017:27017"
    networks:
      - counter

networks:
  counter:

volumes:
  db: